apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: translate-be
  labels:
    app: hello-world
spec:
  replicas: 3
  template:
    metadata:
      labels:
        app: hello-world
        tier: be
        track: dev
    spec:
      volumes:
      - name: gcp-key
        secret:
          secretName: translate-key
      containers:
      - name: hello-world-translate
        image: anners/translate-be
        ports:
        - containerPort: 5001
          name: http
        volumeMounts:
        - name: gcp-key
          mountPath: /var/secrets/gcp
        env:
        - name: GOOGLE_APPLICATION_CREDENTIALS
          value: /var/secrets/gcp/key.json
